# shortcut to the dotfiles area is $ZSH
export ZSH=$HOME/.dotfiles

# source every .zsh file in this rep
for config_file ($ZSH/**/*.zsh) source $config_file

# use .localrc for SUPER SECRET CRAP that you don't
# want in your public, versioned repo.
if [[ -a ~/.localrc ]]
then
  source ~/.localrc
fi

# initialize autocomplete here, otherwise functions won't be loaded
autoload -U compinit
compinit

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
export PATH="$PATH:$HOME/bin" # Add local bin for scripts

export PATH="/usr/local/sbin:$PATH" # Add homebrew's sbin dir to path
#export SPHINXBUILD="/usr/local/opt/sphinx-doc/bin/sphinx-build"
#export PATH="/usr/local/opt/sphinx-doc/bin:$PATH"
export PATH="/usr/local/sbin:/Users/matt/.composer/vendor/bin:$PATH"

#fpath=(/usr/local/share/zsh-completions $fpath)
export PATH="/usr/local/opt/gettext/bin:$PATH"

export NVS_HOME="$HOME/.nvs"
[ -s "$NVS_HOME/nvs.sh" ] && . "$NVS_HOME/nvs.sh"

